### ISSUE TITLE
Commit Template

### ISSUE THREAD

**Issue by lwgray** [OpenGenus/vidsum#13]
:memo:

I have noticed that several of the commits are short of information on "what, why, or how? "   It would make the reviewer's life easier, maybe we could have either/or
* a template for commits, possibly like [this one](https://github.com/sparkbox/standard/tree/master/style/git)
* direction on writing a [good commit](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

**Comment by subkrish** [comment]
@lwgray @AdiChat I can write one. Could I get started immediately?

**Comment by AdiChat** [comment]
Sure @subkrish Go ahead 👍

**Comment by lwgray** [comment]
Thanks @subkrish
