### ISSUE TITLE
Make parameters optional

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/vidsum#2]
Make parameters `video-file` and `subtitle-file` optional. 

[Line 107](https://github.com/OpenGenus/vidsum/blob/master/code/sum.py#L107) : `parser.add_argument('-i', '--video-file', help="Input video file", required=True)` should become `parser.add_argument('-i', '--video-file', help="Input video file")`

Same goes with [Line 108](https://github.com/OpenGenus/vidsum/blob/master/code/sum.py#L108)

This will solve issue #1

**Comment by connorkendrick** [comment]
I can knock this out real quick if you want.

**Comment by TheGamer007** [comment]
This issue seems to have been fixed, but it isn't closed. Is there something left to be done?

**Comment by AdiChat** [comment]
This issue has been resolved 👍

**Comment by lwgray** [comment]
@adiChat Should this issue be closed?

**Comment by AdiChat** [comment]
Yes 😄
