### ISSUE TITLE
Add docstrings to functions

### ISSUE THREAD

**Issue by lwgray** [OpenGenus/vidsum#20]
Overall:
A docstring should be included at the top of code  to summarize project @adiChat This might be good for you to do

Specifically (see example below):  This could be done by other contributers
  1. Docstrings should be added to each function.
  2. The docstrings in each function must include argument type with short description
  3. The docstrings in each function must include a return type

```python
    def is_cow(sound):
        ''' Checks if cow makes inputted sound 
        Args:
            sound(str): sound the animal makes
        Returns:
            bool: True for success, False otherwise.
        '''
        if sound == 'moo':
            return True
        else:
            return False
```

**Comment by yashasingh** [comment]
I would like to work on this.

**Comment by AdiChat** [comment]
@yashasingh Go for it. 👍

**Comment by luisdcb97** [comment]
If the function does not explicitly return do we still need to provide a description beyond returns None?

**Comment by lwgray** [comment]
I think that for the functions that don't return anything, just include a general description of the function and it's inputs.   I would exclude the Returns portion of the docstring in these functions. @AdiChat what do you think?  Also, don't use Returns None.  None is an object in python. 

Please chime in if you think it should be handled differently

**Comment by AdiChat** [comment]
I agree 👍

**Comment by lwgray** [comment]
Need to reopen issue... I found several minor issues with the docstrings and will submit a PR

**Comment by AdiChat** [comment]
Sure 👍
