### ISSUE TITLE
WindowsError: Can't remove file

### ISSUE THREAD

**Issue by lwgray** [OpenGenus/vidsum#38]
Expected Behavior
--------------------
We expect sum.py to delete original mp4 and srt files unless otherwise specified

Current Behavior
-----------------
Traceback (most recent call last):
   File "sum.py", line 252, in <module>
      os.remove(movie_filename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'1.mp4'

Possible Solution
------------------
I do not know 😞 

Steps to Reproduce the Problem
------------------------------------
1.  Git clone vidsum onto windows machine
2.  pip install -r requirements.txt
3.  python sum.py -u https://www.youtube.com/watch?v=xRJCOz3AfYY

Detailed Description
-----------------------
Upon running sum.py on a windows 10 platform, the script is interrupted with a windowsError stating that the removal of files can't take place because one of the file is still in use.

Specifications
----------------
* Platform: Windows 10

**Comment by AdiChat** [comment]
## Cause of error:

 `VideoFileClip()` of `moviepy` library

The error arises at [Line 153](https://github.com/OpenGenus/vidsum/blob/master/code/sum.py#L153): `input_video = VideoFileClip(filename)`

A detailed discussion regarding this behaviour exists at `moviepy` repository: [see this](https://github.com/Zulko/moviepy/issues/596)

## Possible solution

The _immediate solution_, in my opinion, would be to generate the summarized video in a child process that is: execute the statement ([Line 244](https://github.com/OpenGenus/vidsum/blob/master/code/sum.py#L244)) `get_summary(filename=movie_filename, subtitles=subtitle_filename)` in a child process and kill the process immediately after its execution that is before we attempt to delete the download files.

**Comment by ilimugur** [comment]
I'd like to work on this, unless the issue is already taken.

**Comment by AdiChat** [comment]
Sure @ilimugur Go ahead 👍

**Comment by ilimugur** [comment]
Ahead I went, and created a pull request. Tried the fix on a machine running Windows and it seems to have fixed the issue.
