### ISSUE TITLE
Pytube - DoesNotExist Exception

### ISSUE THREAD

**Issue by lwgray** [OpenGenus/vidsum#4]
Exception produced when running:
python sum.py -u https://www.youtube.com/watch?v=o8NPllzkFhE

Exception
+++++++++++
raise DoesNotExist('No videos met this criteria.')
pytube.exceptions.DoesNotExist: No videos met this criteria.
+++++++++++

Solution:
Line 118 - download_video parameter should be 'url' not args.video_file

**Comment by AdiChat** [comment]
Thanks for identifying the issue. 👍
