### ISSUE TITLE
Issue and Pull request template

### ISSUE THREAD

**Issue by guptarohit** [OpenGenus/vidsum#43]
There is no Issue and Pull request template in .github, it can give a idea to contributors about details required to make the issues and pull requests. Also it will make things organised?

I can add them, with reference given in this post https://github.com/blog/2111-issue-and-pull-request-templates ,
https://github.com/stevemao/github-issue-templates

**Comment by AdiChat** [comment]
Sure @guptarohit Go for it 👍
