### ISSUE TITLE
Download subtitles of a YouTube video

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/vidsum#9]
Download the subtitles of a YouTube video as `video.srt`

To achieve this, use `youtube-dl` with the `--write-auto-sub` option
The solution should go at [Line 124](https://github.com/OpenGenus/vidsum/blob/master/code/sum.py#L124)

Other solutions are warmly welcomed as well.

**Comment by matheuscr30** [comment]
I will do this

**Comment by kalbhor** [comment]
Has this been solved? If not, I'd like to work on it.
